exclude_tree = [
  ".hypothesis",
  "scripts/",
  "__pycache__/",
  ".coverage",
  ".grobl.tokens.json",
  ".grobl.config.json",
  ".pre-commit-config.yaml",
  ".coverage",
  "*.pyc",
  "*.egg-info",
  "*.ipynb",
  ".git/",
  ".gitmodules",
  ".groblignore",
  ".pytest_cache/",
  ".venv/",
  ".coverage.xml",
  "ruff.default.toml",
  "uv.lock",
  "yarn.lock",
]
exclude_print = [".gitignore"]
include_tree_tags = "tree"
include_file_tags = "file"
